version: '3'
services:
  flask-app:
    build:
      context: ./flaskApp
      dockerfile: ./Dockerfile/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flaskApp:/app
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  data: