version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mariadb:10.6
    container_name: mariadb_db
    restart: always
    environment:
      MARIADB_DATABASE: laravel
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: laravel
      MARIADB_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
