version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      mynetwork:
        ipv4_address: 172.21.0.3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: 172.21.0.3
      PMA_PORTS: 3306
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  data:

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16